"""Unit tests for the Phase 1.1 document loaders.

These run against real files: the Markdown / text fixtures are
checked in under `tests/evals/fixtures/sample_docs/`, while the PDF
and DOCX fixtures are auto-generated by `tests/conftest.py`'s
session-scoped fixture using `reportlab` and `python-docx`.

Heavy parsers (`pypdf`, `python-docx`) might not be installed in
every dev environment, so we `pytest.importorskip` on them where
they matter, ensuring the suite is robust to a partial install while
still failing CI loudly if the canonical environment is missing
deps.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

from src.ingestion.loaders import (
    DocxLoader,
    DocumentLoader,
    MarkdownLoader,
    PDFLoader,
    ScannedPDFLoader,
    TextLoader,
    get_loader,
)


_FIXTURES = Path(__file__).resolve().parents[1] / "evals" / "fixtures" / "sample_docs"


def _ocr_runtime_available() -> bool:
    """True iff both `pytesseract` + `pdf2image` Python packages import
    AND the `tesseract` binary is on PATH. OCR tests skip cleanly when
    any of those is missing.
    """
    try:
        import pdf2image  # noqa: F401
        import pytesseract

        pytesseract.get_tesseract_version()
        return True
    except Exception:  # noqa: BLE001
        return False


# ─── PDF ─────────────────────────────────────────────────────────────────


class TestPDFLoader:
    @pytest.fixture(autouse=True)
    def _require_pypdf(self) -> None:
        pytest.importorskip("pypdf")

    # ─── Text-only mode (default) ────────────────────────────────────

    async def test_load_two_page_pdf(self) -> None:
        loader = PDFLoader()
        blocks = await loader.load(str(_FIXTURES / "sample_pdf_simple.pdf"))
        assert len(blocks) == 2
        assert all(isinstance(b, str) for b in blocks)

    async def test_load_multipage_preserves_order(self) -> None:
        loader = PDFLoader()
        blocks = await loader.load(str(_FIXTURES / "sample_pdf_multipage.pdf"))
        assert len(blocks) == 5
        # Each fixture page contains its 1-indexed page number — confirm
        # the order isn't shuffled.
        for i, block in enumerate(blocks, start=1):
            assert f"Page {i}" in block, f"page {i} text missing: {block!r}"

    async def test_missing_file_raises_file_not_found(self) -> None:
        loader = PDFLoader()
        with pytest.raises(FileNotFoundError):
            await loader.load("definitely/not/there.pdf")

    async def test_malformed_pdf_raises_value_error(self, tmp_path: Path) -> None:
        # Not a real PDF — pypdf should reject the header.
        bad = tmp_path / "fake.pdf"
        bad.write_bytes(b"not actually a pdf")
        loader = PDFLoader()
        with pytest.raises(ValueError):
            await loader.load(str(bad))

    async def test_text_only_mode_does_not_import_ocr_stack(self) -> None:
        """Pure text extraction must NOT import pytesseract / pdf2image.

        We pop both from `sys.modules` first so an earlier OCR-flavored
        test in the same suite can't fool the check, then assert
        neither was re-imported after a text-only load.
        """
        sys.modules.pop("pytesseract", None)
        sys.modules.pop("pdf2image", None)
        loader = PDFLoader(enable_ocr_fallback=False)
        await loader.load(str(_FIXTURES / "sample_pdf_simple.pdf"))
        assert "pytesseract" not in sys.modules
        assert "pdf2image" not in sys.modules

    # ─── Hybrid mode (enable_ocr_fallback=True) ──────────────────────

    async def test_hybrid_mode_on_text_pdf_skips_ocr(self) -> None:
        """A real text PDF should never trigger OCR fallback. The
        loader returns the same blocks as text-only mode — we don't
        need OCR even to be installed."""
        sys.modules.pop("pytesseract", None)
        sys.modules.pop("pdf2image", None)
        loader = PDFLoader(enable_ocr_fallback=True)
        blocks = await loader.load(str(_FIXTURES / "sample_pdf_simple.pdf"))
        assert len(blocks) == 2
        # extract_text() succeeded → OCR stack still un-imported.
        assert "pytesseract" not in sys.modules
        assert "pdf2image" not in sys.modules

    async def test_hybrid_mode_on_scanned_pdf_falls_back_to_ocr(self) -> None:
        """Image-only PDF: text layer is empty → hybrid OCRs each page."""
        if not _ocr_runtime_available():
            pytest.skip("tesseract / pytesseract / pdf2image not installed")
        scanned = _FIXTURES / "sample_pdf_scanned.pdf"
        if not scanned.exists():
            pytest.skip("scanned PDF fixture not generated (PIL/reportlab missing)")

        loader = PDFLoader(enable_ocr_fallback=True)
        blocks = await loader.load(str(scanned))
        assert len(blocks) >= 1
        # The OCR'd text should contain at least one of the strings we
        # drew into the image. We assert on a lowercased substring to
        # tolerate tesseract's case quirks.
        joined = "\n".join(blocks).lower()
        assert any(
            phrase in joined
            for phrase in ("scanned", "ocr", "fixture", "text layer")
        ), f"OCR produced no recognizable content. blocks={blocks!r}"

    async def test_hybrid_mode_helpful_error_when_ocr_missing(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """If OCR fallback fires but pytesseract isn't installed, the
        loader should raise ImportError with install instructions —
        NOT a generic exception."""
        if _ocr_runtime_available():
            pytest.skip("OCR is installed; this test only runs when it's missing")
        # Generate a fake "scanned" PDF (no text layer) so fallback triggers.
        scanned = _FIXTURES / "sample_pdf_scanned.pdf"
        if not scanned.exists():
            pytest.skip("scanned PDF fixture not generated")
        loader = PDFLoader(enable_ocr_fallback=True)
        with pytest.raises(ImportError, match="tesseract|poppler|pytesseract|pdf2image"):
            await loader.load(str(scanned))


# ─── ScannedPDFLoader (OCR-only, batch) ──────────────────────────────────


class TestScannedPDFLoader:
    @pytest.fixture(autouse=True)
    def _require_ocr(self) -> None:
        if not _ocr_runtime_available():
            pytest.skip("tesseract / pytesseract / pdf2image not installed")

    async def test_ocr_extracts_text_from_scanned_pdf(self) -> None:
        scanned = _FIXTURES / "sample_pdf_scanned.pdf"
        if not scanned.exists():
            pytest.skip("scanned PDF fixture not generated")
        loader = ScannedPDFLoader()
        blocks = await loader.load(str(scanned))
        assert len(blocks) >= 1
        joined = "\n".join(blocks).lower()
        # Sanity: at least one of the source phrases came through OCR.
        assert any(
            phrase in joined
            for phrase in ("scanned", "ocr", "fixture", "text layer")
        ), f"OCR produced no recognizable content. blocks={blocks!r}"

    def test_default_language_is_english(self) -> None:
        loader = ScannedPDFLoader()
        assert loader.ocr_language == "eng"

    def test_custom_language_stored(self) -> None:
        loader = ScannedPDFLoader(ocr_language="deu")
        assert loader.ocr_language == "deu"

    async def test_missing_file_raises_file_not_found(self) -> None:
        loader = ScannedPDFLoader()
        with pytest.raises(FileNotFoundError):
            await loader.load("does/not/exist.pdf")


# ─── Markdown ────────────────────────────────────────────────────────────


class TestMarkdownLoader:
    async def test_splits_on_h2_headers(self) -> None:
        loader = MarkdownLoader()
        blocks = await loader.load(str(_FIXTURES / "rag_guide.md"))
        # `rag_guide.md` has 4 H2 sections; allow some leeway in case
        # the file evolves. We only assert > 1 to lock in "splits".
        assert len(blocks) > 1
        # First block should start with the H2 line.
        for block in blocks:
            # Every emitted section either starts with `##` (proper
            # H2 section) or contains the H1 title block (the slice
            # before the first H2). Both are fine.
            assert block.startswith("#") or block.startswith("##")

    async def test_file_with_no_h2_returns_single_block(self, tmp_path: Path) -> None:
        md = tmp_path / "no_h2.md"
        md.write_text("# Title only\n\nSome prose without any H2 sections.\n")
        loader = MarkdownLoader()
        blocks = await loader.load(str(md))
        assert len(blocks) == 1
        assert "Title only" in blocks[0]

    async def test_preserves_inline_formatting(self, tmp_path: Path) -> None:
        # Make sure the loader doesn't strip `*`, `-`, `>` and friends.
        md = tmp_path / "format.md"
        md.write_text("## S\n\n- bullet\n- *italic*\n\n> quoted\n")
        loader = MarkdownLoader()
        blocks = await loader.load(str(md))
        body = "\n".join(blocks)
        assert "- bullet" in body
        assert "*italic*" in body
        assert "> quoted" in body

    async def test_missing_file_raises_file_not_found(self) -> None:
        loader = MarkdownLoader()
        with pytest.raises(FileNotFoundError):
            await loader.load("missing.md")


# ─── Text ────────────────────────────────────────────────────────────────


class TestTextLoader:
    async def test_single_block_with_line_breaks_preserved(self) -> None:
        loader = TextLoader()
        blocks = await loader.load(str(_FIXTURES / "prompt_engineering.txt"))
        # TextLoader returns ONE block; the chunker splits later.
        assert len(blocks) == 1
        # Multi-line content present.
        assert "\n" in blocks[0]

    async def test_missing_file_raises_file_not_found(self) -> None:
        loader = TextLoader()
        with pytest.raises(FileNotFoundError):
            await loader.load("missing.txt")

    async def test_invalid_utf8_raises_unicode_error(self, tmp_path: Path) -> None:
        bad = tmp_path / "bad.txt"
        # 0xFF is not valid UTF-8 anywhere.
        bad.write_bytes(b"hello \xff world")
        loader = TextLoader()
        with pytest.raises(UnicodeDecodeError):
            await loader.load(str(bad))


# ─── DOCX ────────────────────────────────────────────────────────────────


class TestDocxLoader:
    @pytest.fixture(autouse=True)
    def _require_docx(self) -> None:
        pytest.importorskip("docx")

    async def test_extracts_multiple_paragraphs(self) -> None:
        loader = DocxLoader()
        blocks = await loader.load(str(_FIXTURES / "sample_document.docx"))
        # Generated DOCX has heading + 3 body paragraphs + sub-heading
        # → at least 4 non-empty paragraphs.
        assert len(blocks) >= 4
        assert all(isinstance(b, str) for b in blocks)
        # Empty paragraphs should be filtered out.
        assert all(b.strip() for b in blocks)

    async def test_missing_file_raises_file_not_found(self) -> None:
        loader = DocxLoader()
        with pytest.raises(FileNotFoundError):
            await loader.load("missing.docx")

    async def test_malformed_docx_raises_value_error(self, tmp_path: Path) -> None:
        bad = tmp_path / "fake.docx"
        bad.write_bytes(b"not actually a docx (zip) file")
        loader = DocxLoader()
        with pytest.raises(ValueError):
            await loader.load(str(bad))


# ─── Factory ─────────────────────────────────────────────────────────────


class TestGetLoader:
    @pytest.mark.parametrize(
        ("path", "expected_cls"),
        [
            ("doc.pdf", PDFLoader),
            ("notes.md", MarkdownLoader),
            ("README.markdown", MarkdownLoader),
            ("research.txt", TextLoader),
            ("paper.docx", DocxLoader),
        ],
    )
    def test_dispatches_on_extension(
        self, path: str, expected_cls: type[DocumentLoader]
    ) -> None:
        assert isinstance(get_loader(path), expected_cls)

    def test_case_insensitive_extension(self) -> None:
        # `.PDF`, `.MD`, etc. should still resolve to the right loader.
        assert isinstance(get_loader("DOC.PDF"), PDFLoader)
        assert isinstance(get_loader("Notes.MD"), MarkdownLoader)

    def test_unknown_extension_raises_value_error(self) -> None:
        with pytest.raises(ValueError, match="Unsupported file format"):
            get_loader("data.xyz")

    # ─── pdf_type dispatch ──────────────────────────────────────────

    def test_pdf_type_text_returns_text_only_pdf_loader(self) -> None:
        loader = get_loader("file.pdf", pdf_type="text")
        assert isinstance(loader, PDFLoader)
        assert loader.enable_ocr_fallback is False

    def test_pdf_type_scanned_returns_scanned_pdf_loader(self) -> None:
        loader = get_loader("file.pdf", pdf_type="scanned")
        assert isinstance(loader, ScannedPDFLoader)

    def test_pdf_type_auto_returns_hybrid_pdf_loader(self) -> None:
        loader = get_loader("file.pdf", pdf_type="auto")
        assert isinstance(loader, PDFLoader)
        assert loader.enable_ocr_fallback is True

    def test_pdf_type_default_is_auto(self) -> None:
        # No `pdf_type` kwarg → auto → hybrid loader.
        loader = get_loader("file.pdf")
        assert isinstance(loader, PDFLoader)
        assert loader.enable_ocr_fallback is True

    def test_invalid_pdf_type_raises_value_error(self) -> None:
        with pytest.raises(ValueError, match="Invalid pdf_type"):
            get_loader("file.pdf", pdf_type="bogus")

    def test_ocr_language_propagates(self) -> None:
        loader = get_loader("file.pdf", pdf_type="scanned", ocr_language="deu")
        assert isinstance(loader, ScannedPDFLoader)
        assert loader.ocr_language == "deu"

    def test_pdf_type_ignored_for_non_pdf(self) -> None:
        # Passing pdf_type for a non-PDF extension should NOT crash — we
        # silently ignore it so the same request shape works for any file.
        loader = get_loader("notes.md", pdf_type="scanned")
        assert isinstance(loader, MarkdownLoader)
